version: '3.3'

volumes:
  pg_data:
  static:
  frontend:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    image: acunathink/vink_backend
    env_file: .env
    volumes:
      - static:/backend/
    depends_on:
      - db

  frontend:
    env_file: .env
    image: acunathink/vink_frontend
    volumes:
      - frontend:/app/result_build/

  nginx:
    image: acunathink/vink_gateway
    env_file: .env
    volumes:
      - frontend:/usr/share/nginx/html/
      - static:/backend/
    depends_on:
      - backend
    ports:
      - 8000:80
