# Generated by Django 5.0.3 on 2024-03-31 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Номер телефона должен быть в формате: '+999999999'. Допускается до 15 цифр.",
                                regex="^\\+\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_added", models.DateTimeField(auto_now=True)),
                ("tg_id", models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
