# Generated by Django 5.0.3 on 2024-03-27 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
