# Generated by Django 5.0.3 on 2024-04-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.CharField(
                choices=[("assistant", "system"), ("user", "user")],
                max_length=20,
            ),
        ),
    ]
