# Generated by Django 5.0.3 on 2024-04-03 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotYgpt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bot_name",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        verbose_name="Имя ассистента",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        max_length=64, verbose_name="API Ключ GPT-модели"
                    ),
                ),
                (
                    "catalog_id",
                    models.CharField(
                        max_length=64, verbose_name="Идентификатор каталога"
                    ),
                ),
                (
                    "uri",
                    models.CharField(
                        default="gpt://",
                        max_length=16,
                        verbose_name="URL-префикс адреса модели",
                    ),
                ),
                (
                    "model_base",
                    models.CharField(
                        blank=True,
                        default="/yandexgpt-lite/latest",
                        max_length=32,
                        null=True,
                        verbose_name="адрес используемой модели",
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.5,
                        help_text="Число от 0 до 1. Низкие значения дают более простые ответы",
                        verbose_name="Коэффициент креативности",
                    ),
                ),
                (
                    "answer_len",
                    models.IntegerField(
                        default=500,
                        help_text="Количество символов (от 0 до 2000)",
                        verbose_name="Допустимая длинна ответа",
                    ),
                ),
                (
                    "promt",
                    models.CharField(
                        default="Ты онлайн консультант в чате поддержки пользователей.",
                        max_length=1024,
                        verbose_name="Инструкция к работе",
                    ),
                ),
                (
                    "url_api",
                    models.CharField(
                        default="https://llm.api.cloud.yandex.net/foundationModels/v1/completion",
                        max_length=128,
                        verbose_name="адрес запроса к API YandexGPT",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_open", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "0"),
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                        ],
                        default=3,
                        help_text="Оценка работы оператора от 0 до 5",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to="user_profile.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project",
                    models.CharField(
                        default="setup",
                        max_length=64,
                        unique=True,
                        verbose_name="настройки",
                    ),
                ),
                (
                    "active_bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settings",
                        to="chat.botygpt",
                        verbose_name="дежурный бот",
                    ),
                ),
            ],
        ),
    ]
